name: FastAPI run 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fastapi-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Assurez-vous que la version correspond à celle que vous utilisez

      - name: Install Backend Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Start Backend Server
        run: uvicorn main:app --reload & 

      # Exécuter les tests
      - name: Test with pytest
        run: |
          pip install pytest
          pytest test_main.py
